services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - mongo

  caddy:
    image: caddy:2-alpine
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./docker/caddy/Caddyfile.prod:/etc/caddy/Caddyfile
      - .:/var/www/html
      - caddy_data:/data
      - caddy_config:/config
    environment:
      APP_DOMAIN: ${APP_DOMAIN}
    depends_on:
      - php

  mongo:
    image: mongo:7
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - mongo_data:/data/db
    # MongoDB non exposé à l'extérieur

volumes:
  mongo_data:
  caddy_data:
  caddy_config:
